server:
  port: 8002
  name: report-converter
  url: http://localhost:8002
  os: windows
  
db:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: test-report
  sslmode: disable
  timezone: Asia/Jakarta