server:
  port: 8002
  name: report-converter
  url: https://report-converter.example.com
  os: windows
  
db:
  host: localhost
  port: 5432
  user: postgres
  password: your_password_here
  dbname: report-converter
  sslmode: disable
  timezone: Asia/Jakarta