server:
  port: 8002
  name: report-converter
  url: https://converter-report.avolut.com
  os: windows
  
db:
  host: prasi.avolut.com
  port: 8741
  user: postgres
  password: gEJIfovgvDAroHhqRiKhYVvrkn2OqXfF3tw8xJmnvw7JhrZgN24pTD9iWMIUIUL6
  dbname: report-converter
  sslmode: disable
  timezone: Asia/Jakarta